module.exports = [
  {
    id: 1,
    title: '',
    description: '',
    imageSrc: '../../public/images/unsplash/albert-vincent-wu-SnAy-Tdn4tM-unsplash.jpg',
    width: 600,
    height: 400,
  },
  {
    id: 2,
    title: '',
    description: '',
    imageSrc: '../../public/images/unsplash/duane-mendes-UIyzjfekpQ4-unsplash.jpg',
    width: 600,
    height: 400,
  },
  {
    id: 3,
    title: '',
    description: '',
    imageSrc: '../../public/images/unsplash/graham-mansfield-E-hXjz5O3Zk-unsplash.jpg',
    width: 600,
    height: 400,
  },
  {
    id: 4,
    title: '',
    description: '',
    imageSrc: '../../public/images/unsplash/houcine-ncib-E6PWA9GvIBU-unsplash.jpg',
    width: 600,
    height: 400,
  },
  {
    id: 5,
    title: '',
    description: '',
    imageSrc: '../../public/images/unsplash/jon-tyson-X4BHXXbaFj4-unsplash.jpg',
    width: 600,
    height: 400,
  },
  {
    id: 6,
    title: '',
    description: '',
    imageSrc: '../../public/images/unsplash/joshua-rondeau-ohWlGF9wokg-unsplash(1).jpg',
    width: 600,
    height: 400,
  },
  {
    id: 7,
    title: '',
    description: '',
    imageSrc: '../../public/images/unsplash/laura-chouette-W-7k72ThEr0-unsplash.jpg',
    width: 600,
    height: 400,
  },
  {
    id: 8,
    title: '',
    description: '',
    imageSrc: '../../public/images/unsplash/omid-armin-g4K9KyHGDEc-unsplash.jpg',
    width: 600,
    height: 400,
  },
  {
    id: 9,
    title: '',
    description: '',
    imageSrc: '../../public/images/unsplash/roman-shilin-CTz3o-IqeoI-unsplash.jpg',
    width: 600,
    height: 400,
  },
  {
    id: 10,
    title: '',
    description: '',
    imageSrc: '../../public/images/unsplash/sarah-khan-OjgLBz7znRE-unsplash.jpg',
    width: 600,
    height: 400,
  },
  {
    id: 11,
    title: '',
    description: '',
    imageSrc: '../../public/images/unsplash/sour-moha-tSP10XOSIAQ-unsplash.jpg',
    width: 600,
    height: 400,
  },
  {
    id: 12,
    title: '',
    description: '',
    imageSrc: '../../public/images/unsplash/tyler-nix-3OG8ywzgjJY-unsplash.jpg',
    width: 600,
    height: 400,
  }
]