module.exports = [ 
  {
    id: 1,
    title: 'The Samantha',
    description: 'One of the hottest summer hats of 2021' ,
    width: 3919,
    height: 4898, 
    pathURL: 'https://unsplash.com/photos/CTz3o-IqeoI',
    credit: 'Roman Shilin',
    creditURL: 'https://unsplash.com/@romashilin',
    imageSrc: '/images/unsplash/roman-shilin-CTz3o-IqeoI-unsplash.jpg',
  },

  {
    id: 2,
    title: 'The Essentials',
    description: 'Make sure everyone sees you in the MUST HAVE spring accessories ',
    width: 2304,
    height: 4096, 
    pathURL: 'https://unsplash.com/photos/W-7k72ThEr0',
    credit: 'Laura Chouette',
    creditURL: 'https://unsplash.com/@laurachouette',
    imageSrc: '/images/unsplash/laura-chouette-W-7k72ThEr0-unsplash.jpg',
  },

  {
    id: 3,
    title: 'The Graham',
    description: 'Feel the vibes in this signature spring look ',
    width: 5304,
    height: 7952,
    pathURL: 'https://unsplash.com/photos/E-hXjz5O3Zk',
    credit: 'Graham Mansfield',
    creditURL: 'https://unsplash.com/@grahammansfield1',
    imageSrc: '/images/unsplash/graham-mansfield-E-hXjz5O3Zk-unsplash.jpg',
  },

  {
    id: 4,
    title: 'The Charlotte',
    description: 'This simple yet elegant ensemble is perfect for work or play',
    width: 4000,
    height: 6016,
    pathURL: 'https://unsplash.com/photos/E6PWA9GvIBU',
    credit: 'Houcine Ncib',
    creditURL: 'https://unsplash.com/@houcinencibphotography',
    imageSrc: '/images/unsplash/houcine-ncib-E6PWA9GvIBU-unsplash.jpg',
  },

  {
    id: 5,
    title: 'The Ellie',
    description: 'Go against the grain with this stylish city ensemble',
    width: 4000,
    height: 6000,
    pathURL: 'https://unsplash.com/photos/g4K9KyHGDEc',
    credit: 'Omid Armin',
    creditURL: 'https://unsplash.com/@omidarmin',
    imageSrc: '/images/unsplash/omid-armin-g4K9KyHGDEc-unsplash.jpg',
  },

  {
    id: 6,
    title: 'The Tyler',
    description: 'Stay classy in this hip look',
    width: 3467,
    height: 5200,
    pathURL: 'https://unsplash.com/photos/3OG8ywzgjJY',
    credit: 'Tyler Nix',
    creditURL: 'https://unsplash.com/@jtylernix',
    imageSrc: '/images/unsplash/tyler-nix-3OG8ywzgjJY-unsplash.jpg',
  },

  {
    id: 7,
    title: 'The Duane',
    description: 'Roll with style in these south of the border inspired flip flops',
    width: 2240,
    height: 3181,
    pathURL: 'https://unsplash.com/photos/UIyzjfekpQ4',
    credit: 'Duane Mendes',
    creditURL: 'https://unsplash.com/@duanemendes',
    imageSrc: '/images/unsplash/duane-mendes-UIyzjfekpQ4-unsplash.jpg',
  },

  {
    id: 8,
    title: 'The Lacey',
    description: 'Feel fun and flirty anywhere with this fierce look',
    width: 4000,
    height: 5000,
    pathURL: 'https://unsplash.com/photos/ohWlGF9wokg',
    credit: 'Joshua Rondeau',
    creditURL: 'https://unsplash.com/@liferondeau',
    imageSrc: '/images/unsplash/joshua-rondeau-ohWlGF9wokg-unsplash(1).jpg',
  },

  {
    id: 9,
    title: 'The Albert',
    description: 'The perfect look for a laid back summer',
    width: 3478,
    height: 5841,
    pathURL: 'https://unsplash.com/photos/SnAy-Tdn4tM',
    credit: 'Albert Vincent Wu',
    creditURL: 'https://unsplash.com/@albertvincentwu',
    imageSrc: '/images/unsplash/albert-vincent-wu-SnAy-Tdn4tM-unsplash.jpg',
  },

  {
    id: 10,
    title: 'The Sarah',
    description: 'Stay cool while looking hot in this fit',
    width: 5304,
    height: 7952,
    pathURL: 'https://unsplash.com/photos/OjgLBz7znRE',
    credit: 'Sarah Khan',
    creditURL: 'https://unsplash.com/@itssarahkhan',
    imageSrc: '/images/unsplash/sarah-khan-OjgLBz7znRE-unsplash.jpg',
  },

  {
    id: 11,
    title: 'The Jon',
    description: 'Cover more ground in style with these killer kicks',
    width: 5184,
    height: 3456,
    pathURL: 'https://unsplash.com/photos/X4BHXXbaFj4',
    credit: 'Jon Tyson',
    creditURL: 'https://unsplash.com/@jontyson',
    imageSrc: '/images/unsplash/jon-tyson-X4BHXXbaFj4-unsplash.jpg',
  },

  {
    id: 12,
    title: 'The Lenny',
    description: 'Put in the work in this style yet flexible athletic ensemble',
    width: 4446,
    height: 6663,
    pathURL: 'https://unsplash.com/photos/tSP10XOSIAQ',
    credit: 'sour moha',
    creditURL: 'https://unsplash.com/@sour_moha',
    imageSrc: '/images/unsplash/sour-moha-tSP10XOSIAQ-unsplash.jpg',
  }
];
